### PR TITLE
gasPrice activated

### PR DESCRIPTION
**Pull request by andreweximchain**

### CODE REVIEW

**Review by eximchain137 — COMMENTED** [review]
add comments, stating removing force to nil gas price

**Review by eximchain137 — COMMENTED** [review]
https://github.com/Eximchain/quorum/pull/1/commits/5916da924114d58e4f637f2ffb68d980cf8c3ea4#diff-a00eec40193556e0c2f37e12cef3ff44L299

need no make sure this doesn't adversely affect private state

**Review by eximchain137 — CHANGES_REQUESTED** [review]
https://github.com/Eximchain/quorum/pull/1/commits/c83359be33505214c8d67f780792735214a6bb1e#diff-f3b0aff3b9bda320ae0a5478d8f5f2efR86

Need to set gas price from GPO here, and if tx fails not the nonce used.

**Comment by Lsquared13** [comment]
We'll wait until next week to pull these changes in. I'm going to run a test network with new infrastructure this weekend. Don't want to change infrastructure and core software at the same time.

**Comment by Lsquared13** [comment]
How do we expect to use the new flags? Looks like they're mostly oracle related except for one. Are certain roles going to need to add them to the supervisor config that runs geth?

**Comment by andreweximchain** [comment]
@eximchain137 
We can't make individual nodes fail to send out transactions if they try to send out a transaction ignoring the GPO recommendation because blockmakers are incentivized to want to collect the transactions that have the best gaspricing. So, in a situation where the network is oversaturated with transactions we can't necessarily tell the difference between a transaction that is being accepted late or a transaction that will never be accepted.

**Comment by andreweximchain** [comment]
@Lsquared13 You shouldn't have to make use of any of the new flags if you don't want to. The gpo stuff as of now doesn't need specialized configuration. Also, I will be looking in to changes regarding setting and controlling gasPrice directly from blockmakers, so in the future there may be some configuration flags but for now you should be able to drop these changes in without changing configurations of terraform.

**Comment by Lsquared13** [comment]
Can you actually submit this PR against this new branch. https://github.com/Eximchain/quorum/tree/eximchain-integration

I think moving away from quorum compatibility demands a new branch

**Comment by Lsquared13** [comment]
Closing this in favor of PR #2 on another branch

**Pull request closed without merging**
